# Generated by Django 6.0.4 on 2026-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id_alumnos', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.TextField(max_length=10)),
                ('apellido', models.TextField(max_length=35)),
                ('nombre', models.TextField(max_length=35)),
                ('edad', models.IntegerField()),
                ('calle', models.TextField(max_length=50)),
                ('altuta', models.IntegerField()),
            ],
        ),
    ]
